name: 'Auto Release'
description: 'Automatically create a release based on commit messages'
inputs:
  title:
    description: 'Title for the release'
    required: false
    default: 'Version $semver'
  tag:
    description: 'Name for the git tag'
    required: false
    default: '$version'
  draft:
    description: 'Whether or not this release should be published as a draft'
    required: false
    default: 'false'
  regex:
    description: 'Pattern the commit message must match to create a release'
    required: false
  prerelease-regex:
    description: 'Pattern the commit message must match to mark the release as a prerelease'
    required: false
outputs:
  released:
    description: 'Whether or not a release was created'
  id:
    description: 'The id of the release'
  version:
    description: 'The version that was released'
  html_url:
    description: 'The URL users can navigate to in order to view the release'
  upload_url:
    description: 'The URL for uploading assets to the release'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'green'
